# Base image
FROM mambaorg/micromamba:2.3.0

# Install Linux packages
USER root
RUN apt-get update && apt-get install -y \
	git \
	libgomp1 \
	libegl1 \
	libgl1 \
	libgl1-mesa-glx \
    libgl1-mesa-dri \
    libglu1-mesa \
    mesa-utils \
	xvfb \
	x11-utils \
    x11-xserver-utils \
	sqlite3 \
	&& rm -rf /var/lib/apt/lists/*

# Create workspace
RUN mkdir -p /workspace && \
	chown -R $MAMBA_USER:$MAMBA_USER /workspace
WORKDIR /workspace
USER $MAMBA_USER

# Set environment activation variable
ENV MAMBA_DOCKERFILE_ACTIVATE=1

# Copy and install environment
COPY --chown=$MAMBA_USER:$MAMBA_USER env_dev.yml /workspace/env_dev.yml
RUN micromamba install -y -n base -f /workspace/env_dev.yml && \
	micromamba clean --all --yes

# # Clone and install Waymo open dataset
# RUN git clone https://github.com/waymo-research/waymo-open-dataset.git /workspace/waymo-od && \
# 	pip install waymo-open-dataset-tf-2-12-0 --no-deps && \
# 	pip install protobuf==3.20.0
