services:
  waymo-od-env:
    user: root
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: waymo-od-image
    container_name: waymo-od-container
    ports:
      - "8001:8001"
    volumes:
      - .:/workspace/hostfiles
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/runtime-mambauser:/tmp/runtime-mambauser
    environment:
      DISPLAY: ${DISPLAY}
      XDG_RUNTIME_DIR: /tmp/runtime-mambauser
      QT_X11_NO_MITSHM: 1
    tty: true
    deploy:
      resources:
        limits:
          memory: 12G