# Base image
FROM mambaorg/micromamba:2.3.0

# Install Linux packages
USER root
RUN apt-get update && apt-get install -y \
	ffmpeg \
	git \
	libgomp1 \
	# libegl1 \
	# libgl1 \
	libosmesa6 \
    libosmesa6-dev \
	libgl1-mesa-glx \
    libgl1-mesa-dri \
    libglu1-mesa \
    mesa-utils \
	# xvfb \
	# x11-utils \
    # x11-xserver-utils \
	sqlite3 \
	v4l-utils \
	&& rm -rf /var/lib/apt/lists/*

# Create workspace
RUN mkdir -p /workspace && \
	chown -R $MAMBA_USER:$MAMBA_USER /workspace
WORKDIR /workspace
USER $MAMBA_USER

# Set environment variables
ENV MAMBA_DOCKERFILE_ACTIVATE=1
ENV LIBGL_ALWAYS_SOFTWARE=1
ENV OPEN3D_RENDERING_ENGINE=OSMesa
ENV OPEN3D_CPU_RENDERING=1
# ENV EGL_PLATFORM=surfaceless # Used for GPU-accelerated rendering

# Copy and install environment
COPY --chown=$MAMBA_USER:$MAMBA_USER env_dev.yml /workspace/env_dev.yml
RUN micromamba install -y -n base -f /workspace/env_dev.yml && \
	micromamba clean --all --yes

# Install Open3D (cannot install via conda in env.yml file since conda
# does not properly expose open3d.visualization.rendering module for 
# headless rendering)
RUN pip install open3d==0.19.0

# Set entrypoint
ENTRYPOINT ["/bin/bash"]