FROM mambaorg/micromamba:2.3.0

# Install Linux packages
USER root
RUN apt-get update && apt-get install -y \
    git

# Create workspace
RUN mkdir -p /workspace && \
	chown -R $MAMBA_USER:$MAMBA_USER /workspace
WORKDIR /workspace
USER $MAMBA_USER

# Copy source code and env files
COPY --chown=$MAMBA_USER:$MAMBA_USER . /workspace

# Copy and install environment
RUN micromamba install -y -n base -f /workspace/env_dev.yml && \
	micromamba clean --all --yes