name: Pylint 3D Semantic Seg

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker container
      run: docker compose -f 3D_semantic_seg/docker-compose.yml up --build -d

    - name: Run pylint inside Docker container
      run: |
        docker compose -f 3D_semantic_seg/docker-compose.yml exec -T waymo-od-env \
          micromamba run -n waymo_open_env \
          bash -c "\
            pip install pylint && \
            cd /workspace/hostfiles &&
            pylint \$(git ls-files 'src/*.py')"

    - name: Tear down Docker container
      run: docker compose -f 3D_semantic_seg/docker-compose.yml down